reorder_imports = true
attr_fn_like_width = 100
chain_width = 120
fn_params_layout = "Vertical"
fn_call_width = 100
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
max_width = 120
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_single_line = false
use_try_shorthand = true
wrap_comments = true