name: Changelog

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: Generate changelog
        run: git cliff --verbose --output CHANGELOG.md --github-repo ${{ github.repository }} --github-token ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'

      - name: Commit
        run: |
          git add CHANGELOG.md Cargo.toml
          git commit -m "chore(changelog): update changelog file [skip ci]"
          git push origin main