name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup problem matcher
        uses: r7kamura/rust-problem-matchers@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build and test
        run: |
          cargo build --verbose
          cargo test --verbose

  check-format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup problem matcher
        uses: r7kamura/rust-problem-matchers@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          default: true
          override: true

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup problem matcher
        uses: r7kamura/rust-problem-matchers@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          default: true
          override: true

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
